'use client';
import { PrivatePortfolio } from './PortfolioPrivacy';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {compareHolding,holdingDiversificationSchema,type HoldingDiversificationInput} from '@/lib/portfolio/amzn';
import {readHoldings,dollars,percent,type Holdings} from '@/lib/holdings';
import {connectedHoldings} from '@/lib/connected-portfolio';
import {usePortfolioSession} from './PortfolioSession';
import {FanChart} from './PortfolioCharts';

const today='';
const defaults:HoldingDiversificationInput={symbol:'AMZN',scope:'Connect or load a private holdings snapshot',asOf:today,total:1000000,holding:700000,basis:0,tax:.25,years:10,holdingReturn:.08,holdingVol:.32,otherReturn:.06,otherVol:.18,correlation:.6};
const key='equity-diversify-holding-comparison-v1';

function AmznDecisionContent(){
 const {snapshot}=usePortfolioSession();
 const [s,S]=useState(defaults),[result,R]=useState<ReturnType<typeof compareHolding>|null>(null),[used,U]=useState<HoldingDiversificationInput|null>(null),[message,M]=useState(''),[busy,B]=useState(false),[sourceHoldings,H]=useState<Holdings|null>(null);
 const symbols=useMemo(()=>sourceHoldings?.positions.filter(p=>p.shares>0).map(p=>p.symbol).sort()??[],[sourceHoldings]);
 useEffect(()=>{if(snapshot){try{const c=connectedHoldings(snapshot);H(c.holdings);if(c.holdings.positions.length){const requested=new URLSearchParams(window.location.search).get('symbol')?.toUpperCase();const current=c.holdings.positions.find(p=>p.symbol===requested)??[...c.holdings.positions].sort((a,b)=>b.shares*b.price-a.shares*a.price)[0];if(current)loadHolding(c.holdings,current.symbol,'connected');}}catch(e){M(e instanceof Error?e.message:'Connected accounts could not be used.');}}else{try{const saved=readHoldings();H(saved);const requested=new URLSearchParams(window.location.search).get('symbol')?.toUpperCase();if(saved){const selected=saved.positions.find(p=>p.symbol===requested&&p.shares>0)??[...saved.positions].filter(p=>p.shares>0).sort((a,b)=>b.shares*b.price-a.shares*a.price)[0];if(selected)loadHolding(saved,selected.symbol,'saved');}else S(v=>({...v,asOf:new Date().toISOString().slice(0,10)}));}catch{/* no saved snapshot */}}},[snapshot]);
 const edit=(k:keyof HoldingDiversificationInput,v:string|number)=>{S({...s,[k]:v});R(null);U(null);};
 function loadHolding(holdings:Holdings,symbol:string,source:'connected'|'saved'){
  const p=holdings.positions.find(x=>x.symbol===symbol);
  if(!p||p.shares<=0)throw new Error(`Add ${symbol} to My holdings first.`);
  S({...s,symbol,scope:holdings.scope,total:holdings.totalValue,holding:p.shares*p.price,basis:p.averageCost==null?0:p.averageCost*p.shares,asOf:holdings.asOf});R(null);U(null);
  M(p.averageCost==null?`Loaded ${symbol} from ${source==='connected'?'connected accounts':'saved holdings'}. Cost basis is unknown; enter an estimate or leave zero for the conservative full-gain assumption.`:`Loaded ${symbol} from ${source==='connected'?'connected accounts':'saved holdings'}. Review the snapshot date and tax assumption.`);
 }
 function loadSelected(){try{let h=sourceHoldings;if(!snapshot&&!h)h=readHoldings();if(!h)throw new Error('Refresh connected accounts or add holdings in My holdings first.');loadHolding(h,s.symbol,snapshot?'connected':'saved');}catch(e){M(e instanceof Error?e.message:'Unable to load this holding.');}}
 function run(){B(true);M('Comparing six allocations across 10,000 matched paths…');setTimeout(()=>{try{const checked=holdingDiversificationSchema.parse(s);R(compareHolding(checked));U(checked);M('Comparison ready. Results depend on the editable assumptions below.');}catch(e){M(e instanceof Error?e.message:'Could not calculate.');}finally{B(false);}},30);}
 function save(){if(!used||!result)return;try{localStorage.setItem(key,JSON.stringify({version:1,input:used,result}));M('Comparison saved privately in this browser.');}catch{M('Browser storage is unavailable.');}}
 function reopen(){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(!x||x.version!==1)throw new Error();const parsed=holdingDiversificationSchema.parse(x.input);S(parsed);U(parsed);R(compareHolding(parsed));M('Saved assumptions reopened. The fixed seed reproduces the comparison; no research call was made.');}catch{M('No valid saved comparison is available.');}}
 const field=(k:keyof HoldingDiversificationInput,label:string,mult=1)=><label key={k}>{label}<input type="number" step="any" value={Number(s[k])*mult} onChange={e=>edit(k,Number(e.target.value)/mult)}/></label>;
 return <><section className="hero compact"><div><p className="eyebrow">HOLDING DIVERSIFICATION</p><h1>What if I reduce a large holding?</h1><p className="lede">Compare keeping it, trimming 25%, 50%, 75% or all at once, and staging a 50% trim. Use the same market paths for every ratio.</p></div></section>
 <section className="panel"><h2>1. Review the selected holding</h2><p>Your connected or saved snapshot loads here automatically. Review it in <Link href="/accounts">Account settings</Link> or <Link href="/holdings">manage your snapshot</Link>. The refresh stays in this tab’s memory and clears on reload. No trade is placed.</p>{sourceHoldings?.coverage==='partial'&&<p className="warning">This portfolio has incomplete exposure or unverified account overlap. The comparison includes known values only; check the account warnings first.</p>}
 <div className="button-row"><label>Large holding<select value={s.symbol} onChange={e=>{if(sourceHoldings)loadHolding(sourceHoldings,e.target.value,snapshot?'connected':'saved');else edit('symbol',e.target.value);}}>{!symbols.includes(s.symbol)&&<option value={s.symbol}>{s.symbol}</option>}{symbols.map(symbol=><option key={symbol} value={symbol}>{symbol}</option>)}</select></label>{!sourceHoldings&&<button onClick={loadSelected}>Load selected holding</button>}<button className="action secondary" onClick={reopen}>Reopen saved comparison</button></div>
 <div className="input-grid"><label>Portfolio scope<input value={s.scope} onChange={e=>edit('scope',e.target.value)}/></label><label>Snapshot date<input type="date" value={s.asOf} onChange={e=>edit('asOf',e.target.value)}/></label>{field('total','Total portfolio ($)')}{field('holding','Selected holding value ($)')}{field('basis','Selected holding total cost basis ($)')}{field('tax','Assumed combined tax on gains (%)',100)}<label>Horizon<select value={s.years} onChange={e=>edit('years',Number(e.target.value))}><option value="5">5 years</option><option value="10">10 years</option><option value="20">20 years</option></select></label></div>
 <p className="muted">Cost basis is not available from every connected account, so check it before modeling taxes. The model applies one tax rate to proportional average basis; it does not select lots or model holding periods, losses, deductions or future tax-law changes.</p>
 <h2>2. Review the assumptions for the selected holding and everything else</h2><div className="input-grid">{field('holdingReturn',`${s.symbol} expected annual return (%)`,100)}{field('holdingVol',`${s.symbol} annual volatility (%)`,100)}{field('otherReturn','Other holdings blended annual return (%)',100)}{field('otherVol','Other holdings blended annual volatility (%)',100)}{field('correlation',`${s.symbol} / other holdings correlation`)}</div><p>The rest of the portfolio is modeled as one blended asset. These starting return, risk and correlation values are illustrative assumptions, not research-derived forecasts. Change them or load historical risk in <Link href="/portfolio">Portfolio Lab</Link>. Funds already contain underlying stocks; their overlap is not estimated here.</p>
 <p className="muted">The staged option sells 12.5% of today’s holding at months 0, 3, 6 and 9. No later rebalancing, new contributions, RSUs, inflation or terminal liquidation tax is modeled. The 10,000 paths are conditional simulations, not predictions or probabilities of what will happen.</p><button disabled={busy} onClick={run}>{busy?'Calculating…':'Compare trim ratios'}</button><p role="status" aria-live="polite">{message}</p></section>
 {result&&used&&<section className="panel"><h2>3. Compare the tradeoffs</h2><p>{used.scope} · snapshot {used.asOf} · {used.years} years · six strategies · 10,000 paths · fixed seed 42971</p><p>Current {used.symbol} weight: <strong>{percent(used.holding/used.total)}</strong>. Cost and taxes are estimates based on the assumptions above.</p>
 <div className="table-wrap"><table><thead><tr><th>Allocation</th><th>Holding weight after initial sale</th><th>Mean modeled sale tax</th><th>Downside (5th)</th><th>Median</th><th>Upside (95th)</th><th>Chance of ending below start</th></tr></thead><tbody>{result.results.map((r,i)=>{const fractions=[0,.25,.5,.75,1,.125],gross=used.holding*fractions[i],tax=Math.max(0,gross-used.basis*gross/used.holding)*used.tax,end=r.years.at(-1)!.percentiles;return <tr key={r.name}><td>{r.name}</td><td>{percent((used.holding-gross)/(used.total-tax))}</td><td>{dollars(r.meanSaleTax)}</td><td>{dollars(end[0])}</td><td>{dollars(end[3])}</td><td>{dollars(end[6])}</td><td>{percent(r.lossProbability)}</td></tr>;})}</tbody></table></div>
 <p>Lower trim ratios retain more upside and downside exposure to {used.symbol}; larger trims reduce that concentration and realize more tax sooner. The highest modeled median is not automatically the best choice.</p><div className="scenario-grid">{result.results.map(r=><FanChart key={r.name} result={r} maxValue={Math.max(...result.results.flatMap(v=>v.years.map(y=>y.percentiles[6])))}/>)}</div><button onClick={save}>Save comparison privately</button><details><summary>Year-by-year median, downside and upside</summary><div className="table-wrap"><table><thead><tr><th>Year</th>{result.results.map(r=><th key={r.name}>{r.name} · 5th / 50th / 95th</th>)}</tr></thead><tbody>{result.results[0].years.map((y,i)=><tr key={y.year}><td>{y.year}</td>{result.results.map(r=><td key={r.name}>{[0,3,6].map(q=>dollars(r.years[i].percentiles[q])).join(' / ')}</td>)}</tr>)}</tbody></table></div></details></section>}</>;
}

export function AmznDecision() { return <PrivatePortfolio><AmznDecisionContent /></PrivatePortfolio>; }
