'use client';
import {useState} from 'react';
import {amznSchema,compareAmzn,type AmznInput} from '@/lib/portfolio/amzn';
import {readHoldings,dollars,percent} from '@/lib/holdings';
import {FanChart} from './PortfolioCharts';
const defaults:AmznInput={scope:'Illustrative portfolio — replace with your figures',asOf:new Date().toISOString().slice(0,10),total:1000000,amzn:700000,basis:350000,sale:300000,tax:.25,years:10,amznReturn:.08,amznVol:.32,otherReturn:.06,otherVol:.18,correlation:.6};
const key='equity-amzn-comparison-v1';
export function AmznDecision(){
 const [s,S]=useState(defaults),[result,R]=useState<ReturnType<typeof compareAmzn>|null>(null),[used,U]=useState<AmznInput|null>(null),[message,M]=useState(''),[busy,B]=useState(false);
 const edit=(k:keyof AmznInput,v:string|number)=>{S({...s,[k]:v});R(null);U(null);};
 function run(){B(true);M('Calculating 10,000 matched paths…');setTimeout(()=>{try{const checked=amznSchema.parse(s);R(compareAmzn(checked));U(checked);M('Comparison ready. Results depend on the assumptions below.');}catch(e){M(e instanceof Error?e.message:'Could not calculate.');}finally{B(false);}},30);}
 function loadHoldings(){try{const h=readHoldings(),p=h?.positions.find(p=>p.symbol==='AMZN');if(!h||!p||p.shares===0)throw new Error('Add an AMZN position in My holdings first.');S({...s,scope:h.scope+' — '+h.coverage+' coverage',asOf:h.asOf,total:h.totalValue,amzn:p.shares*p.price,basis:p.averageCost==null?0:p.averageCost*p.shares});R(null);U(null);M(p.averageCost==null?'Loaded holdings. Cost basis is unknown: enter the total basis before running. Zero means a conservative full-gain assumption.':'Loaded the dated holdings snapshot. Check tax assumptions.');}catch(e){M(e instanceof Error?e.message:'Unable to read holdings.');}}
 function save(){if(!used||!result)return;try{localStorage.setItem(key,JSON.stringify({version:1,input:used,result}));M('Comparison saved privately in this browser.');}catch{M('Browser storage is unavailable.');}}
 function reopen(){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(!x||x.version!==1)throw new Error();const parsed=amznSchema.parse(x.input);S(parsed);U(parsed);R(compareAmzn(parsed));M('Saved assumptions reopened. The fixed seed reproduces the same comparison locally; no research call was made.');}catch{M('No valid saved comparison is available.');}}
 const field=(k:keyof AmznInput,label:string,mult=1)=><label key={k}>{label}<input type="number" step="any" value={Number(s[k])*mult} onChange={e=>edit(k,Number(e.target.value)/mult)}/></label>;
 return <><section className="hero compact"><div><p className="eyebrow">AMZN DIVERSIFICATION</p><h1>Keep, reduce now, or reduce in stages?</h1><p className="lede">Compare concentration, sale taxes and possible long-term wealth using the same market paths.</p></div></section>
 <section className="panel"><h2>1. Set the portfolio you are comparing</h2><p>Starts with illustrative figures. Replace them with a dated snapshot. Future RSUs and unconfirmed sales are excluded. Nothing here submits a trade.</p><div className="button-row"><button onClick={loadHoldings}>Use my private AMZN holding</button><button onClick={reopen}>Reopen saved comparison</button></div><div className="input-grid"><label>Portfolio scope<input value={s.scope} onChange={e=>edit('scope',e.target.value)}/></label><label>Snapshot date<input type="date" value={s.asOf} onChange={e=>edit('asOf',e.target.value)}/></label>{field('total','Total portfolio ($)')}{field('amzn','AMZN market value ($)')}{field('basis','Total AMZN cost basis ($)')}{field('sale','AMZN value to reduce ($)')}{field('tax','Assumed combined tax on gains (%)',100)}<label>Horizon<select value={s.years} onChange={e=>edit('years',Number(e.target.value))}><option value="5">5 years</option><option value="10">10 years</option><option value="20">20 years</option></select></label></div>
 <p className="muted">Sale tax uses proportional average basis, positive gains only and your single assumed tax rate. No lot selection, holding-period rules, losses, deductions or future tax-law changes are modeled. Tax is paid from sale proceeds; the remainder moves to the other investments.</p>
 <h2>2. Review future assumptions</h2><div className="input-grid">{field('amznReturn','AMZN expected annual return (%)',100)}{field('amznVol','AMZN annual volatility (%)',100)}{field('otherReturn','Other investments annual return (%)',100)}{field('otherVol','Other investments annual volatility (%)',100)}{field('correlation','AMZN / other correlation')}</div><p>The other investments are one blended proxy for everything outside AMZN, including the replacement investment. Defaults are illustrative, not historical estimates. If your cash, funds and replacement have different risks, use <a href="/portfolio">Portfolio Lab</a> for a more detailed allocation comparison.</p>
 <p className="muted">Four equal portions of today's share exposure are sold at months 0, 3, 6 and 9. Later proceeds vary with AMZN's price. No subsequent rebalancing, new RSUs or cash flows. Monthly lognormal returns and fixed correlations omit crisis regimes and extreme jumps. Returns are nominal; no inflation, fees or terminal liquidation tax. Loss means finishing below the original portfolio value.</p><button disabled={busy} onClick={run}>{busy?'Calculating…':'Compare three strategies'}</button><p role="status">{message}</p></section>
 {result&&used&&<section className="panel"><h2>3. Compare the tradeoffs</h2><p>{used.scope} · snapshot {used.asOf} · {used.years} years · 10,000 paths · fixed seed 42971</p><p>Current AMZN weight: <strong>{percent(used.amzn/used.total)}</strong>. Reducing now pays approximately <strong>{dollars(Math.max(0,used.sale-used.basis*used.sale/used.amzn)*used.tax)}</strong> in modeled tax.</p>
 <div className="table-wrap"><table><thead><tr><th>Strategy</th><th>AMZN weight just after first sale</th><th>Mean sale tax</th><th>Downside (5th)</th><th>Median</th><th>Upside (95th)</th><th>Chance of ending below start</th></tr></thead><tbody>{result.results.map((r,i)=>{const f=i===0?0:i===1?1:.25,gross=used.sale*f,tax=Math.max(0,gross-used.basis*gross/used.amzn)*used.tax,end=r.years.at(-1)!.percentiles;return <tr key={r.name}><td>{r.name}</td><td>{percent((used.amzn-gross)/(used.total-tax))}</td><td>{dollars(r.meanSaleTax)}</td><td>{dollars(end[0])}</td><td>{dollars(end[3])}</td><td>{dollars(end[6])}</td><td>{percent(r.lossProbability)}</td></tr>;})}</tbody></table></div>
 <p>Keeping AMZN preserves its full upside and downside exposure. Reducing now lowers exposure immediately and realizes tax immediately. Staging spreads the sale dates while retaining more AMZN risk during the first nine months. The highest modeled median is not automatically the best choice.</p>
 <div className="scenario-grid">{result.results.map(r=><FanChart key={r.name} result={r} maxValue={Math.max(...result.results.flatMap(r=>r.years.map(y=>y.percentiles[6])))}/>)}</div><button onClick={save}>Save comparison privately</button><details><summary>Year-by-year median / downside / upside</summary><div className="table-wrap"><table><thead><tr><th>Year</th>{result.results.map(r=><th key={r.name}>{r.name} · 5th / 50th / 95th</th>)}</tr></thead><tbody>{result.results[0].years.map((y,i)=><tr key={y.year}><td>{y.year}</td>{result.results.map(r=><td key={r.name}>{[0,3,6].map(q=>dollars(r.years[i].percentiles[q])).join(' / ')}</td>)}</tr>)}</tbody></table></div></details></section>}</>;
}
