'use client';
import {useEffect,useState} from 'react';
import {HOLDINGS_KEY,holdingsSchema,readHoldings,dollars,type Holdings} from '@/lib/holdings';
const empty:Holdings={version:1,scope:'My selected account',asOf:new Date().toISOString().slice(0,10),coverage:'partial',totalValue:0,cashAvailable:0,positions:[]};
export function HoldingsWorkspace(){
 const [s,set]=useState<Holdings>(empty),[message,msg]=useState(''),[symbol,S]=useState(''),[shares,Q]=useState(''),[price,P]=useState(''),[kind,K]=useState<'stock'|'fund'>('stock');
 useEffect(()=>{try{const saved=readHoldings();if(saved)set(saved);}catch{msg('The saved file could not be read. Import a valid snapshot or enter it again.');}},[]);
 function save(){try{const valid=holdingsSchema.parse(s);localStorage.setItem(HOLDINGS_KEY,JSON.stringify(valid));set(valid);msg('Saved in this browser. Open a stock report to compare an add or trim.');}catch(e){msg(e instanceof Error?e.message:'Unable to save.');}}
 async function importFile(file?:File){if(!file)return;try{if(file.size>500000)throw new Error('Use a file under 500 KB.');const valid=holdingsSchema.parse(JSON.parse(await file.text()));localStorage.setItem(HOLDINGS_KEY,JSON.stringify(valid));set(valid);msg('Imported and saved privately in this browser.');}catch{msg('Could not import. Use the JSON format below; verify the date, positive prices, totals and unique symbols.');}}
 function download(){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='private-holdings.json';a.click();URL.revokeObjectURL(url);}
 return <><section className="hero compact"><div><p className="eyebrow">MY HOLDINGS</p><h1>I already own this.</h1><p className="lede">Record a dated snapshot, then open any holding to compare holding, adding and trimming.</p></div></section>
 <section className="panel"><p>Stored only in this browser. Anyone using this browser profile can read it. Holdings are excluded from company research and shared summaries. This website does not sync with your brokerage.</p>
 <div className="input-grid"><label>Account / portfolio scope<input value={s.scope} onChange={e=>set({...s,scope:e.target.value})}/></label><label>Snapshot date<input type="date" value={s.asOf} onChange={e=>set({...s,asOf:e.target.value})}/></label><label>Account / portfolio total ($)<input type="number" min="0" value={s.totalValue} onChange={e=>set({...s,totalValue:Number(e.target.value)})}/></label><label>Available cash, excluding margin ($)<input type="number" min="0" value={s.cashAvailable} onChange={e=>set({...s,cashAvailable:Number(e.target.value)})}/></label><label>Coverage<select value={s.coverage} onChange={e=>set({...s,coverage:e.target.value as Holdings['coverage']})}><option value="partial">Selected holdings only</option><option value="complete">All holdings in this scope</option></select></label></div>
 <p className="muted">Use prices and an account total from the same time. The total includes cash and unlisted assets. Unlisted symbols remain unknown; record zero shares explicitly when you own none.</p>
 <div className="input-grid"><label>Symbol<input value={symbol} onChange={e=>S(e.target.value.toUpperCase())}/></label><label>Shares<input type="number" min="0" step="any" value={shares} onChange={e=>Q(e.target.value)}/></label><label>Price on snapshot date ($)<input type="number" min="0" step="any" value={price} onChange={e=>P(e.target.value)}/></label><label>Type<select value={kind} onChange={e=>K(e.target.value as 'stock'|'fund')}><option value="stock">Company stock</option><option value="fund">Fund / ETF</option></select></label></div>
 <button onClick={()=>{if(!/^[A-Z][A-Z.\-]{0,9}$/.test(symbol)||shares===''||price===''||Number(shares)<0||Number(price)<=0){msg('Enter a symbol, nonnegative shares and a positive price.');return;}set({...s,positions:[...s.positions.filter(p=>p.symbol!==symbol),{symbol,shares:Number(shares),price:Number(price),kind}]});msg('Position updated. Save the snapshot to use it in research.');}}>Add / replace position</button>
 <div className="table-wrap"><table><thead><tr><th>Holding</th><th>Shares</th><th>Value</th><th>Review</th></tr></thead><tbody>{s.positions.map(p=><tr key={p.symbol}><td>{p.symbol} · {p.kind}</td><td>{p.shares.toLocaleString('en-US',{maximumFractionDigits:6})}</td><td>{dollars(p.shares*p.price)}</td><td><a href={`/company/${p.symbol}`}>Research</a>{' '}<button aria-label={`Remove ${p.symbol}`} onClick={()=>set({...s,positions:s.positions.filter(q=>q.symbol!==p.symbol)})}>Remove</button></td></tr>)}</tbody></table></div>
 <div className="button-row"><button onClick={save}>Save private snapshot</button><button onClick={download}>Download private JSON</button><button onClick={()=>{localStorage.removeItem(HOLDINGS_KEY);set(empty);msg('Saved holdings cleared from this browser.');}}>Clear saved holdings</button></div><p role="status">{message}</p>
 <label>Import private snapshot (JSON)<input type="file" accept=".json,application/json" onChange={e=>void importFile(e.target.files?.[0])}/></label>
 <details><summary>Import format</summary><p>Manual entry works without a file. To import, use this format with your own values. Dates and prices must match the total. This is an example only.</p><pre>{JSON.stringify({...empty,totalValue:10000,cashAvailable:5000,positions:[{symbol:'MSFT',shares:10,price:400,kind:'stock'}]},null,2)}</pre></details></section></>;
}
