"use client";
import { useState } from "react";
import type { ResearchRun } from "@/lib/types";
import { callPayoff, investmentDecision } from "@/lib/decision";
const usd = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });
export function InvestmentChoices({ run }: { run: ResearchRun }) {
  const decision = investmentDecision(run);
  const [strategy, setStrategy] = useState<"call" | "spread">("call");
  const [values, setValues] = useState({ strike: "", shortStrike: "", debit: "", contracts: "1", targetPrice: "", expiration: "", budget: "" });
  const [result, setResult] = useState<ReturnType<typeof callPayoff> | null>(null);
  const [error, setError] = useState("");
  const update = (key: keyof typeof values, value: string) => { setValues(old => ({ ...old, [key]: value })); setResult(null); setError(""); };
  return <section aria-labelledby="investment-choices"><h2 id="investment-choices">Buy now, wait, or use options?</h2>
    <div className="panel"><h3>{decision.action}</h3><p>{decision.reason}</p><p>{decision.instrument}</p><p><strong>For aggressive growth:</strong> a longer-dated call can amplify an upside move, but the whole premium can be lost. A call debit spread costs less than the equivalent long call in exchange for capped upside. Neither fixes a weak investment case.</p></div>
    <div className="scenario-grid choices">
      <article className="panel"><h3>Shares</h3><p>Best match when you believe in long-term growth but cannot predict when it will arrive. No expiration or option premium decay.</p><p><strong>Risk:</strong> the company can still lose most or all of its value. Use money you can leave invested through a decline.</p></article>
      <article className="panel"><h3>Longer-dated call</h3><p>A candidate to investigate when you have a strong bullish thesis and a deadline. Compare expirations after the expected catalyst; 6–18 months is a research starting range, not a recommended contract. Calls near or below the share price generally rely less on a very large jump than far-out-of-the-money calls.</p><p><strong>Risk:</strong> you can be right about direction and still lose from slow timing or falling expected volatility. Maximum option loss before exercise is the premium plus fees.</p></article>
      <article className="panel"><h3>Call debit spread</h3><p>Buy a call and sell a higher-strike call with the same expiry and contract size. A candidate for a moderate, time-bound rise when the uncapped call is too expensive.</p><p><strong>Trade-off:</strong> lower net premium, capped gains, and assignment/expiration risk. Robinhood generally requires Level 3 access for spreads.</p></article>
    </div>
    <p className="muted">Robinhood quotes are not connected. No current contract, premium, implied volatility or liquidity has been verified. This comparison uses the saved report and is not a personalized allocation. Avoid treating short-dated or far-out-of-the-money calls as a substitute for missing evidence.</p>
    <p><a href="https://robinhood.com/us/en/support/articles/360001227566/" target="_blank" rel="noreferrer">Robinhood options access and quotes</a> · <a href="https://robinhood.com/us/en/support/articles/advanced-options-strategies/" target="_blank" rel="noreferrer">Robinhood spread mechanics and risks</a></p>
    <details className="panel"><summary>Compare an actual Robinhood quote</summary><p>Enter a quote you have checked in Robinhood. This calculates possible outcomes; it does not verify the quote or select a trade. Use the ask to estimate a call purchase, or long-call ask minus short-call bid for a conservative spread debit. Check volume, open interest, bid–ask width, expected volatility and earnings dates separately.</p>
      <form onSubmit={event => { event.preventDefault(); try { setResult(callPayoff({ strategy, ...Object.fromEntries(Object.entries(values).map(([k,v]) => [k, k === "expiration" ? v : Number(v)])) } as Parameters<typeof callPayoff>[0])); setError(""); } catch (err) { setResult(null); setError(err instanceof Error ? err.message : "Check the inputs."); } }}>
        <label>Strategy<select value={strategy} onChange={event => { setStrategy(event.target.value as "call" | "spread"); setResult(null); }}><option value="call">Buy a call</option><option value="spread">Call debit spread</option></select></label>
        <div className="input-grid">{([ ["strike", "Long call strike ($)"], ...(strategy === "spread" ? [["shortStrike", "Short call strike ($)"]] : []), ["debit", strategy === "spread" ? "Net debit per share ($)" : "Call premium per share ($)"], ["contracts", "Number of contracts"], ["targetPrice", "Your assumed stock price at expiry ($)"], ["budget", "Maximum dollars you can lose"], ["expiration", "Expiration date"] ] as [keyof typeof values, string][]).map(([key,label]) => <label key={key}>{label}<input required type={key === "expiration" ? "date" : "number"} min={key === "targetPrice" ? "0" : key === "contracts" ? "1" : "0.01"} step={key === "contracts" ? "1" : "0.01"} value={values[key]} onChange={event => update(key,event.target.value)} /></label>)}</div>
        <button className="action" type="submit">Calculate possible outcomes</button>
      </form>
      {error && <p role="alert" className="warning">{error}</p>}
      {result && <div aria-live="polite"><div className="scenario-grid"><div className="metric"><strong>{usd(result.maxLoss)}</strong><span>Premium at risk</span></div><div className="metric"><strong>{usd(result.breakEven)}</strong><span>Stock break-even at expiration</span></div><div className="metric"><strong>{usd(result.profitAtTarget)}</strong><span>Profit/loss at your assumed stock price</span></div></div><p>Maximum theoretical gain: {result.maxGain == null ? "uncapped for a long call" : usd(result.maxGain)}. Your loss budget allows at most {result.affordableContracts} contract(s), before fees.</p>{result.budgetExceeded && <p className="warning">This exceeds the loss budget you entered. Reduce the size or wait.</p>}{result.daysToExpiry < 90 && <p className="warning">This expires in {result.daysToExpiry} days. Short time remaining makes the outcome especially sensitive to timing and premium decay.</p>}<p className="muted">Expiration payoff only; assumes standard, unadjusted 100-share US equity option contracts. Excludes fees, taxes, slippage and exercise funding. A spread’s theoretical loss limit assumes both legs remain intact; early assignment or one leg exercising can create stock exposure. Review or close positions before expiration if you cannot fund exercise. This is not a probability forecast.</p></div>}
    </details>
  </section>;
}
