"use client";
import { useState } from "react";
import type { ResearchRun } from "@/lib/types";
import { callPayoff, investmentDecision } from "@/lib/decision";
const usd = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });
export function InvestmentChoices({ run }: { run: ResearchRun }) {
  const decision = investmentDecision(run);
  const [owned, setOwned] = useState(false);
  const [goal, setGoal] = useState("growth");
  const bullish = decision.score !== null && decision.score >= 70;
  const bearish = decision.score !== null && decision.score < 40;
  const strategyIdea = owned && goal === "protect" ? "Compare a protective put or collar" : owned && goal === "income" ? "Compare a covered call only at a price you would accept for selling your shares" : bullish ? "Shares first; compare a long call or call debit spread if timing and premiums support the thesis" : bearish ? owned ? "Review selling or reducing shares before paying for a hedge" : "Avoid new shares; a put or put debit spread requires a separate, timed bearish thesis" : "Wait on new directional options; the stock evidence does not establish an attractive entry";
  const [strategy, setStrategy] = useState<"call" | "spread">("call");
  const [values, setValues] = useState({ strike: "", shortStrike: "", debit: "", contracts: "1", targetPrice: "", expiration: "", budget: "" });
  const [result, setResult] = useState<ReturnType<typeof callPayoff> | null>(null);
  const [error, setError] = useState("");
  const update = (key: keyof typeof values, value: string) => { setValues(old => ({ ...old, [key]: value })); setResult(null); setError(""); };
  return <section aria-labelledby="investment-choices"><h2 id="investment-choices">Buy now, wait, or use options?</h2>
    <div className="panel"><label><input type="checkbox" checked={owned} onChange={e=>setOwned(e.target.checked)}/> I already own shares</label><label>My objective<select value={goal} onChange={e=>setGoal(e.target.value)}><option value="growth">Growth</option><option value="protect">Protect my investment</option><option value="income">Generate income</option></select></label><h3>{owned ? decision.ownedAction : decision.action}</h3><p>{decision.reason}</p><h3>{strategyIdea}</h3><p>{decision.instrument}</p>{!owned && goal !== "growth" && <p>Protection and covered-call income require an existing shareholding. A cash-secured put is an obligation to buy shares, not protection from a decline.</p>}</div>
    <details className="panel"><summary>Compare the strategy trade-offs</summary><div className="two-col">
      <article><h3>Shares or a bullish call spread</h3><p>Shares fit a growth thesis without an expiry deadline. A long call can lose its entire premium even if the company eventually succeeds. A call debit spread buys a call and sells a higher-strike call at the same expiry: it lowers cost but caps gains. Neither is selected without current quotes and a catalyst timeline.</p></article>
      <article><h3>Protective put or collar · existing shares</h3><p>A purchased put can limit downside below its strike until expiry, at the cost of a premium. A collar adds a covered call to help fund that put, sacrificing upside above the call strike. Compare selling some shares with paying repeatedly for insurance.</p></article>
      <article><h3>Covered call · income from existing shares</h3><p>Sell a call only against shares you own and are willing to sell at the strike. Standard contracts usually require 100 shares each. Income is limited; most stock downside remains, and shares can be called away early. This can conflict with aggressive growth.</p></article>
      <article><h3>Put or put debit spread · bearish view</h3><p>A long put benefits from a sufficiently large, timely decline; its premium can be lost. A put debit spread buys a higher-strike put and sells a lower-strike put at the same expiry, capping both theoretical gain and premium risk. A low stock score alone does not establish a profitable option price.</p></article>
      <article><h3>Cash-secured put · conditional entry</h3><p>Only consider this if you want to buy the shares at the strike and reserve enough cash to do so. Premium income does not remove the obligation to buy after a large decline; gains are limited while losses can be substantial.</p></article>
    </div><p>Before choosing a contract: verify expiry after the catalyst, bid/ask spread, volume, open interest, expected volatility, earnings date, exercise obligations and maximum loss. No live chain is connected, so the tool cannot rank exact contracts yet.</p><a href="https://robinhood.com/us/en/support/articles/options-collateral/" target="_blank" rel="noreferrer">Robinhood collateral requirements</a></details>
    <p className="muted">Robinhood quotes are not connected. No current contract, premium, implied volatility or liquidity has been verified. This comparison uses the saved report and is not a personalized allocation. Avoid treating short-dated or far-out-of-the-money calls as a substitute for missing evidence.</p>
    <p><a href="https://robinhood.com/us/en/support/articles/360001227566/" target="_blank" rel="noreferrer">Robinhood options access and quotes</a> · <a href="https://robinhood.com/us/en/support/articles/advanced-options-strategies/" target="_blank" rel="noreferrer">Robinhood spread mechanics and risks</a></p>
    <details className="panel"><summary>Compare an actual Robinhood quote</summary><p>Enter a quote you have checked in Robinhood. This calculates possible outcomes; it does not verify the quote or select a trade. Use the ask to estimate a call purchase, or long-call ask minus short-call bid for a conservative spread debit. Check volume, open interest, bid–ask width, expected volatility and earnings dates separately.</p>
      <form onSubmit={event => { event.preventDefault(); try { setResult(callPayoff({ strategy, ...Object.fromEntries(Object.entries(values).map(([k,v]) => [k, k === "expiration" ? v : Number(v)])) } as Parameters<typeof callPayoff>[0])); setError(""); } catch (err) { setResult(null); setError(err instanceof Error ? err.message : "Check the inputs."); } }}>
        <label>Strategy<select value={strategy} onChange={event => { setStrategy(event.target.value as "call" | "spread"); setResult(null); }}><option value="call">Buy a call</option><option value="spread">Call debit spread</option></select></label>
        <div className="input-grid">{([ ["strike", "Long call strike ($)"], ...(strategy === "spread" ? [["shortStrike", "Short call strike ($)"]] : []), ["debit", strategy === "spread" ? "Net debit per share ($)" : "Call premium per share ($)"], ["contracts", "Number of contracts"], ["targetPrice", "Your assumed stock price at expiry ($)"], ["budget", "Maximum dollars you can lose"], ["expiration", "Expiration date (YYYY-MM-DD)"] ] as [keyof typeof values, string][]).map(([key,label]) => <label key={key}>{label}<input required type={key === "expiration" ? "text" : "number"} placeholder={key === "expiration" ? "YYYY-MM-DD" : undefined} min={key === "targetPrice" ? "0" : key === "contracts" ? "1" : "0.01"} step={key === "contracts" ? "1" : "0.01"} value={values[key]} onChange={event => update(key,event.target.value)} /></label>)}</div>
        <button className="action" type="submit">Calculate possible outcomes</button>
      </form>
      {error && <p role="alert" className="warning">{error}</p>}
      {result && <div aria-live="polite"><div className="scenario-grid"><div className="metric"><strong>{usd(result.maxLoss)}</strong><span>Premium at risk</span></div><div className="metric"><strong>{usd(result.breakEven)}</strong><span>Stock break-even at expiration</span></div><div className="metric"><strong>{usd(result.profitAtTarget)}</strong><span>Profit/loss at your assumed stock price</span></div></div><p>Maximum theoretical gain: {result.maxGain == null ? "uncapped for a long call" : usd(result.maxGain)}. Your loss budget allows at most {result.affordableContracts} contract(s), before fees.</p>{result.budgetExceeded && <p className="warning">This exceeds the loss budget you entered. Reduce the size or wait.</p>}{result.daysToExpiry < 90 && <p className="warning">This expires in {result.daysToExpiry} days. Short time remaining makes the outcome especially sensitive to timing and premium decay.</p>}<p className="muted">Expiration payoff only; assumes standard, unadjusted 100-share US equity option contracts. Excludes fees, taxes, slippage and exercise funding. A spread’s theoretical loss limit assumes both legs remain intact; early assignment or one leg exercising can create stock exposure. Review or close positions before expiration if you cannot fund exercise. This is not a probability forecast.</p></div>}
    </details>
  </section>;
}
