'use client';
import {useEffect,useRef,useState} from 'react';
import {loadArchive,saveRun} from '@/lib/archive';
import type {ResearchRun} from '@/lib/types';
import {screenUniverse,rankOpportunities} from '@/lib/opportunities';
export function Opportunities(){
 const started=useRef(false);
 const [runs,R]=useState<ResearchRun[]>([]),[busy,B]=useState(false),[message,M]=useState(''),[failures,F]=useState<string[]>([]);
 useEffect(()=>{void loadArchive().then(x=>{if(!started.current){R(x.runs);M(x.message);}});},[]);
 async function screen(){started.current=true;B(true);F([]);let completed=0;const queue=[...screenUniverse];async function worker(){while(queue.length){const stock=queue.shift()!;try{const r=await fetch(`/api/analyze?ticker=${stock.symbol}`,{cache:'no-store'});if(!r.ok)throw new Error();const run=await r.json() as ResearchRun;if(!run.id||run.ticker!==stock.symbol)throw new Error();saveRun(run);R(old=>[...old.filter(x=>x.ticker!==stock.symbol),run]);}catch{F(old=>[...old,stock.symbol]);}finally{completed++;M(`Completed ${completed} of ${screenUniverse.length} companies. Keep this page open while screening.`);}}}await Promise.all([worker(),worker()]);M('Screen complete. Missing evidence and failed reports are shown; no minimum number of buys is imposed.');B(false);}
 const rows=rankOpportunities(runs).filter(x=>screenUniverse.some(s=>s.symbol===x.run.ticker));
 const qualify=(x:typeof rows[number])=>x.decision.action==='Buy candidate'&&(x.run.evidenceAssessment?.score??0)>=80&&(Date.now()-Date.parse(x.run.marketAsOf??''))/86400000>=0&&(Date.now()-Date.parse(x.run.marketAsOf??''))/86400000<=7;
 return <><section className="hero compact"><div><p className="eyebrow">FIND OPPORTUNITIES</p><h1>Compare stocks across sectors.</h1><p className="lede">Rank ten selected companies by the same evidence-based method. A useful screen can return fewer than five buys.</p></div></section><section className="panel"><h2>Five sectors, two companies each</h2><p>{screenUniverse.map(s=>s.symbol).join(' · ')}</p><p>This is a selected large-company universe, not a search of the entire market. Screening generates ten new research reports and uses the configured model and data allowances. It can take several minutes.</p><button disabled={busy} onClick={()=>void screen()}>{busy?'Screening…':'Run cross-sector screen'}</button><p role="status">{message}</p>{failures.length>0&&<p>Reports that could not complete: {failures.join(', ')}.</p>}</section><section className="panel"><h2>{rows.filter(qualify).length} buy candidates with broad evidence coverage</h2><p>Qualification: investment score at least 70, evidence coverage at least 80 and a quote no more than seven days old. Evidence coverage is not a probability of profit. Different sectors can still fall together.</p>{rows.length===0?<p>No saved reports for this screen yet.</p>:<div className="table-wrap"><table><thead><tr><th>Symbol / sector</th><th>Investment view</th><th>Evidence coverage</th><th>Price date / report date</th><th>Why / next step</th></tr></thead><tbody>{rows.map(x=><tr key={x.run.id}><td><a href={`/research/${x.run.id}`}>{x.run.ticker}</a><br/>{x.sector}</td><td>{x.decision.action}<br/>{x.decision.score??'Unrated'}{x.decision.score!=null?'/100':''}{qualify(x)&&<p><strong>Meets screen</strong></p>}</td><td>{x.run.evidenceAssessment?`${x.run.evidenceAssessment.score}/100`:'Older method — rerun'}</td><td>{x.run.marketAsOf?.slice(0,10)||'Unavailable'}<br/>{x.run.analyzedAt.slice(0,10)}</td><td>{x.decision.reason}<br/>{x.decision.missing.length>0&&`Missing: ${x.decision.missing.join(', ')}`}</td></tr>)}</tbody></table></div>}<p>Results are saved to your archive when storage is available. Opening a saved report does not generate another analysis. Current financial data and valuation assumptions must be reviewed before an investment decision.</p></section></>;
}
