'use client';
import {useEffect,useRef,useState} from 'react';
import {loadArchive} from '@/lib/archive';
import type {ResearchRun} from '@/lib/types';
import {screenUniverse,rankOpportunities} from '@/lib/opportunities';
import {loadChecks,runChecks} from '@/lib/watchlist';
import {rankChecks,type QuickCheck} from '@/lib/quick-check';
import {sectorGroups} from '@/lib/peer-valuation';
export function Opportunities(){
 const started=useRef(false);
 const [runs,R]=useState<ResearchRun[]>([]),[busy,B]=useState(false),[message,M]=useState(''),[failures,F]=useState<string[]>([]);
 useEffect(()=>{void loadArchive().then(x=>{if(!started.current){R(x.runs);M(x.message);}});},[]);
 const stop=useRef(false);const [checks,C]=useState<Record<string,QuickCheck>>({});const [all,A]=useState(false);
 useEffect(()=>{C(loadChecks());},[]);
 const universe=all?[...new Set(sectorGroups().flatMap(g=>g.symbols))]:screenUniverse.map(s=>s.symbol);
 async function screen(){started.current=true;B(true);F([]);stop.current=false;const today=new Date().toISOString().slice(0,10);const todo=universe.filter(t=>!loadChecks()[t]?.checkedAt.startsWith(today));await runChecks(todo,m=>{M(m);C(loadChecks());},stop);C(loadChecks());B(false);}
 const quick=rankChecks(universe.map(t=>checks[t]).filter(Boolean));
 const rows=rankOpportunities(runs).filter(x=>screenUniverse.some(s=>s.symbol===x.run.ticker));
 const qualify=(x:typeof rows[number])=>x.decision.action==='Buy candidate'&&(x.run.evidenceAssessment?.score??0)>=80&&(Date.now()-Date.parse(x.run.marketAsOf??''))/86400000>=0&&(Date.now()-Date.parse(x.run.marketAsOf??''))/86400000<=7;
 return <><section className="hero compact"><div><p className="eyebrow">FIND OPPORTUNITIES</p><h1>Compare stocks across sectors.</h1><p className="lede">Screen large companies across sectors for free, then spend full research reports only on the best candidates. A useful screen can return no buys.</p></div></section><section className="panel"><h2>Step 1 · Quick screen (no AI credits)</h2><label><input type="checkbox" checked={all} onChange={e=>A(e.target.checked)}/> Screen all {new Set(sectorGroups().flatMap(g=>g.symbols)).size} companies across {sectorGroups().length} sectors (default: ten across five sectors)</label><p>{universe.join(' · ')}</p><p>Values each company from SEC filings, the current price and consensus forecasts with the app&apos;s deterministic DCF. Results are cached for the day. Then run a full report (paid, daily-capped) only for the most promising names.</p><div className="button-row"><button disabled={busy} onClick={()=>void screen()}>{busy?'Screening…':'Run quick screen'}</button>{busy&&<button className="action secondary" onClick={()=>{stop.current=true;}}>Stop</button>}</div><p role="status">{message}</p>{failures.length>0&&<p>Could not complete: {failures.join(', ')}.</p>}
{quick.length>0&&<div className="table-wrap"><table><thead><tr><th>Company</th><th>Zone</th><th>Price</th><th>Base intrinsic</th><th>Buy below</th><th>Upside</th><th>Growth</th><th>Step 2</th></tr></thead><tbody>{quick.map(q=><tr key={q.ticker}><td><strong>{q.ticker}</strong><br/><small>{q.sector}</small></td><td>{q.zone}</td><td>${q.price.toFixed(2)}</td><td>{q.valuation.available?`$${q.valuation.perShare.base.toFixed(2)}`:'—'}</td><td>{q.buyBelow!=null?`$${q.buyBelow.toFixed(2)}`:'—'}</td><td>{q.upsidePct!=null?`${q.upsidePct>0?'+':''}${q.upsidePct.toFixed(1)}%`:'—'}</td><td>{q.metrics.consensusRevenueGrowth!=null?`${q.metrics.consensusRevenueGrowth}%`:'—'}</td><td><a href={`/company/${encodeURIComponent(q.ticker)}`}>Full report</a></td></tr>)}</tbody></table></div>}</section><section className="panel"><h2>Step 2 · Full reports: {rows.filter(qualify).length} buy candidates with broad evidence coverage</h2><p>Qualification: investment score at least 70, evidence coverage at least 80 and a quote no more than seven days old. Evidence coverage is not a probability of profit. Different sectors can still fall together.</p>{rows.length===0?<p>No saved reports for this screen yet.</p>:<div className="table-wrap"><table><thead><tr><th>Symbol / sector</th><th>Investment view</th><th>Evidence coverage</th><th>Price date / report date</th><th>Why / next step</th></tr></thead><tbody>{rows.map(x=><tr key={x.run.id}><td><a href={`/research/${x.run.id}`}>{x.run.ticker}</a><br/>{x.sector}</td><td>{x.decision.action}<br/>{x.decision.score??'Unrated'}{x.decision.score!=null?'/100':''}{qualify(x)&&<p><strong>Meets screen</strong></p>}</td><td>{x.run.evidenceAssessment?`${x.run.evidenceAssessment.score}/100`:'Older method — rerun'}</td><td>{x.run.marketAsOf?.slice(0,10)||'Unavailable'}<br/>{x.run.analyzedAt.slice(0,10)}</td><td>{x.decision.reason}<br/>{x.decision.missing.length>0&&`Missing: ${x.decision.missing.join(', ')}`}</td></tr>)}</tbody></table></div>}<p>Results are saved to your archive when storage is available. Opening a saved report does not generate another analysis. Current financial data and valuation assumptions must be reviewed before an investment decision.</p></section></>;
}
