"use client";
import {useEffect,useState} from "react";
import type {SimulationInput} from "@/lib/portfolio/engine";
import type {HistoryEstimate} from "@/lib/portfolio/history";
import type {PortfolioSnapshot,PortfolioRequest} from "@/lib/portfolio/model";
import {FanChart,Histogram,wealth} from "./PortfolioCharts";
const percent=(v:number)=>`${(v*100).toFixed(1)}%`;
const KEY="equity-portfolio-snapshots-v1";
const presets={A:[0,1,0,0],B:[0,.5,.5,0],C:[.7,.3,0,0],D:[.35,.45,0,.2]};
const names={A:"100% VTI",B:"50% VTI / 50% QQQ",C:"70% AMZN / 30% VTI",D:"35% AMZN / 45% VTI / 20% cash"};
const initial:SimulationInput={assets:[{symbol:"AMZN",expectedReturn:.08,volatility:.32},{symbol:"VTI",expectedReturn:.06,volatility:.18},{symbol:"QQQ",expectedReturn:.07,volatility:.25},{symbol:"CASH",expectedReturn:.02,volatility:0}],correlation:[[1,.65,.75,0],[.65,1,.9,0],[.75,.9,1,0],[0,0,0,1]],strategies:[{name:names.C,weights:presets.C,rebalance:"none"},{name:names.D,weights:presets.D,rebalance:"none"}],initialValue:1000000,years:10,paths:10000,seed:42,monthlyContribution:0,goal:2000000};
type Saved={id:string;createdAt:string;names:string[];local?:PortfolioSnapshot};
function localRuns():PortfolioSnapshot[]{try{return JSON.parse(localStorage.getItem(KEY)||"[]");}catch{return [];}}
export function PortfolioLab(){
 const [input,setInput]=useState<SimulationInput>(initial),[history,setHistory]=useState<HistoryEstimate|undefined>(),[windowYears,setWindowYears]=useState(5),[returnSource,setReturnSource]=useState("Illustrative forward assumptions, not research-derived forecasts."),[riskSource,setRiskSource]=useState("Illustrative risk assumptions. Load historical estimates or edit before using."),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[snapshot,setSnapshot]=useState<PortfolioSnapshot|null>(null),[saved,setSaved]=useState<Saved[]>([]),[newSymbol,setNewSymbol]=useState("");
 async function refresh(){const locals=localRuns();let cloud:Saved[]=[];try{const r=await fetch("/api/portfolio",{cache:"no-store"});if(r.ok)cloud=(await r.json()).runs;}catch{}setSaved([...cloud,...locals.filter(l=>!cloud.some(c=>c.id===l.id)).map(l=>({id:l.id,createdAt:l.createdAt,names:l.request.input.strategies.map(s=>s.name),local:l}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));}
 useEffect(()=>{refresh();},[]);
 function edit(next:SimulationInput){setInput(next);setAck(false);setSnapshot(null);setMessage("");}
 function applyPreset(k:number,key:keyof typeof presets){const assets=initial.assets.map(a=>({...input.assets.find(x=>x.symbol===a.symbol)??a}));edit({...input,assets,correlation:input.assets.map(a=>a.symbol).join()===initial.assets.map(a=>a.symbol).join()?input.correlation:initial.correlation,strategies:input.strategies.map((s,i)=>({...s,weights:i===k?presets[key]:assets.map(a=>s.weights[input.assets.findIndex(x=>x.symbol===a.symbol)]??0),name:i===k?names[key]:s.name}))});if(input.assets.length!==4){setHistory(undefined);setRiskSource("Illustrative correlations restored by sample preset; review assumptions.");}}
 async function loadHistory(){setBusy(true);setMessage("Loading aligned monthly adjusted prices. Provider limits may apply…");try{const r=await fetch("/api/portfolio/history",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:input.assets.map(a=>a.symbol),years:windowYears}),signal:AbortSignal.timeout(180000)});const body=await r.json();if(!r.ok)throw new Error(body.error);const e:HistoryEstimate=body.estimate;setHistory(e);setInput({...input,assets:input.assets.map(a=>({...a,volatility:e.assets.find(x=>x.symbol===a.symbol)!.volatility})),correlation:e.correlation});setRiskSource(`Historical monthly log-return volatility and correlations: ${e.start} to ${e.end}, ${e.observations} common observations.`);setAck(false);setSnapshot(null);setMessage("Historical volatility and correlations loaded. Forward returns remain your editable assumptions.");}catch(e){setMessage(e instanceof Error?e.message:"History unavailable. Manual inputs remain usable.");}finally{setBusy(false);}}
 async function run(){setBusy(true);setMessage("Simulating 10,000 common market paths for both strategies…");setSnapshot(null);try{const request:PortfolioRequest={input:input as PortfolioRequest["input"],assumptions:{returnSource,riskSource,history,acknowledged:true}};const r=await fetch("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request),signal:AbortSignal.timeout(75000)});const result=await r.json();if(!r.ok)throw new Error(result.error);setSnapshot(result);let stored=true;try{localStorage.setItem(KEY,JSON.stringify([result,...localRuns().filter(s=>s.id!==result.id)].slice(0,20)));}catch{stored=false;}setMessage(result.storage==="cloud"?"Simulation saved privately in the cloud. Reopening does not rerun it.":stored?"Cloud save unavailable. Saved in this browser; export a copy to keep it.":"Could not save this result. Export it before leaving.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Simulation failed.");}finally{setBusy(false);}}
 async function open(s:Saved){setBusy(true);try{let data=s.local;if(!data){const r=await fetch(`/api/portfolio/${encodeURIComponent(s.id)}`,{cache:"no-store"});if(!r.ok)throw new Error("Saved simulation could not be opened.");data=await r.json();}const value=data!;setInput(value.request.input);setHistory(value.request.assumptions.history);setReturnSource(value.request.assumptions.returnSource);setRiskSource(value.request.assumptions.riskSource);setSnapshot(value);setAck(false);setMessage(`Opened saved ${value.modelVersion} run from ${new Date(value.createdAt).toLocaleString()}. No new simulation.`);}catch(e){setMessage(e instanceof Error?e.message:"Could not open saved run.");}finally{setBusy(false);}}
 const totals=input.strategies.map(s=>s.weights.reduce((a,b)=>a+b,0)),validWeights=totals.every(t=>Math.abs(t-1)<1e-8);
 return <>
 <p className="eyebrow">PORTFOLIO LAB · MARKET MONTE CARLO</p><h1>What changes if I diversify?</h1><p className="lede">Compare possible outcomes for two allocations under the same market scenarios. See the trade-offs, not a declared winner.</p>
 <p className="warning">Phase 1 uses hypothetical, long-only USD portfolios. Samples are not your holdings. Outcomes are nominal and pre-tax; taxes, trading costs, leverage, options and unvested shares are not modeled. This is a simulation, not a backtest or forecast guarantee.</p>
 <fieldset disabled={busy} className="portfolio-fieldset">
 <section className="panel"><h2>1. Define the decision</h2><div className="input-grid"><label>Starting portfolio value ($)<input type="number" min="1" value={input.initialValue} onChange={e=>edit({...input,initialValue:Number(e.target.value)})}/></label><label>Investment horizon<select value={input.years} onChange={e=>edit({...input,years:Number(e.target.value)})}>{[5,10,20].map(n=><option key={n} value={n}>{n} years</option>)}</select></label></div>
 <p>Compare reallocations of the same starting wealth. Enter position weights; each column must total 100%. Cash is a separate asset. A sale’s taxes and different starting contributions require later decision-cost modeling.</p>
 <div className="two-col">{input.strategies.map((s,k)=><div key={k}><label>Strategy {k+1} name<input value={s.name} maxLength={70} onChange={e=>edit({...input,strategies:input.strategies.map((v,i)=>i===k?{...v,name:e.target.value}:v)})}/></label><label>Load sample<select value="" onChange={e=>applyPreset(k,e.target.value as keyof typeof presets)}><option value="" disabled>Choose a sample allocation</option>{Object.entries(names).map(([key,name])=><option key={key} value={key}>{key}: {name}</option>)}</select></label><label>Rebalancing<select value={s.rebalance} onChange={e=>edit({...input,strategies:input.strategies.map((v,i)=>i===k?{...v,rebalance:e.target.value as typeof v.rebalance}:v)})}><option value="none">None — let weights drift</option><option value="annual">Annual — restore target weights</option><option value="monthly">Monthly — restore target weights</option></select></label></div>)}</div>
 <div className="table-wrap"><table><thead><tr><th>Asset</th>{input.strategies.map((s,i)=><th key={i}>{s.name} weight %</th>)}</tr></thead><tbody>{input.assets.map((a,j)=><tr key={a.symbol}><td>{a.symbol}</td>{input.strategies.map((s,k)=><td key={k}><input aria-label={`${a.symbol} strategy ${k+1} weight`} type="number" min="0" max="100" step="1" value={Number((s.weights[j]*100).toFixed(6))} onChange={e=>edit({...input,strategies:input.strategies.map((v,i)=>i===k?{...v,weights:v.weights.map((w,l)=>l===j?Number(e.target.value)/100:w)}:v)})}/></td>)}</tr>)}<tr><th>Total</th>{totals.map((t,i)=><td key={i}>{percent(t)}{Math.abs(t-1)>1e-8?" — must equal 100%":""}</td>)}</tr></tbody></table></div>
 <div className="toolbar"><label>Add asset (up to 8)<input value={newSymbol} placeholder="NVDA" maxLength={10} onChange={e=>setNewSymbol(e.target.value.toUpperCase().trim())}/></label><button className="action secondary" disabled={input.assets.length>=8||!/^[A-Z][A-Z.\-]{0,9}$/.test(newSymbol)||input.assets.some(a=>a.symbol===newSymbol)} onClick={()=>{edit({...input,assets:[...input.assets,{symbol:newSymbol,expectedReturn:0,volatility:0}],correlation:[...input.correlation.map(r=>[...r,0]),[...input.assets.map(()=>0),1]],strategies:input.strategies.map(s=>({...s,weights:[...s.weights,0]}))});setHistory(undefined);setRiskSource("Manual inputs; new asset added with zero placeholders. Load history or set all risks explicitly.");setNewSymbol("");}}>Add asset</button></div></section>
 <section className="panel"><h2>2. Review the assumptions</h2><p>Starting numbers are illustrative, not recommendations. Loading history changes volatility and correlations only. Expected returns are annual expected growth assumptions, not historical CAGR carried forward.</p><div className="toolbar"><label>Historical estimation window<select value={windowYears} onChange={e=>setWindowYears(Number(e.target.value))}>{[1,3,5,10].map(y=><option key={y} value={y}>{y} years</option>)}</select></label><button className="action secondary" onClick={loadHistory}>Load historical risk estimates</button></div>
 <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Forward annual return %</th><th>Annual volatility %</th><th>Historical CAGR</th></tr></thead><tbody>{input.assets.map((a,i)=><tr key={a.symbol}><td>{a.symbol}</td><td><input aria-label={`${a.symbol} expected return`} type="number" step=".1" value={Number((a.expectedReturn*100).toFixed(5))} onChange={e=>edit({...input,assets:input.assets.map((v,j)=>j===i?{...v,expectedReturn:Number(e.target.value)/100}:v)})}/></td><td><input aria-label={`${a.symbol} volatility`} disabled={a.symbol==="CASH"} type="number" min="0" max="150" step=".1" value={Number((a.volatility*100).toFixed(5))} onChange={e=>{edit({...input,assets:input.assets.map((v,j)=>j===i?{...v,volatility:Number(e.target.value)/100}:v)});setRiskSource("User-edited risk assumptions; historical estimates, if shown, are reference only.");}}/></td><td>{a.symbol==="CASH"?"Not estimated":history?percent(history.assets.find(x=>x.symbol===a.symbol)?.cagr??0):"Not loaded"}</td></tr>)}</tbody></table></div>
 <details><summary>Correlation matrix — assets move together</summary><p>1 means perfect co-movement; 0 means no modeled relationship; −1 means opposite movement. Edited values must form a valid matrix. Correlations are fixed through time in this MVP.</p><div className="table-wrap"><table><thead><tr><th>Asset</th>{input.assets.map(a=><th key={a.symbol}>{a.symbol}</th>)}</tr></thead><tbody>{input.assets.map((a,i)=><tr key={a.symbol}><th>{a.symbol}</th>{input.assets.map((b,j)=><td key={b.symbol}><input aria-label={`${a.symbol} correlation with ${b.symbol}`} type="number" min="-1" max="1" step=".01" disabled={j<=i||a.symbol==="CASH"||b.symbol==="CASH"} value={Number(input.correlation[i][j].toFixed(4))} onChange={e=>{const c=input.correlation.map(r=>[...r]);c[i][j]=c[j][i]=Number(e.target.value);edit({...input,correlation:c});setRiskSource("User-edited risk assumptions; historical estimates, if shown, are reference only.");}}/></td>)}</tr>)}</tbody></table></div></details>
 <div className="input-grid"><label>Why these forward returns?<textarea value={returnSource} maxLength={1200} onChange={e=>{setReturnSource(e.target.value);setAck(false);setSnapshot(null);}}/></label><label>Risk assumptions source / limitations<textarea value={riskSource} maxLength={1200} onChange={e=>{setRiskSource(e.target.value);setAck(false);setSnapshot(null);}}/></label></div>
 {history&&<details><summary>Historical source, dates and estimation details</summary><p>{history.start}–{history.end} · {history.observations} common monthly returns. {history.warning}</p><ul>{history.assets.filter(a=>a.symbol!=="CASH").map(a=><li key={a.symbol}>{a.symbol}: historical CAGR {percent(a.cagr)}, arithmetic monthly-return mean × 12 {percent(a.arithmeticAnnual)}, log-return volatility × √12 {percent(a.volatility)}.</li>)}</ul><ul>{history.sources.map(s=><li key={s.symbol}><a href={s.source} target="_blank" rel="noreferrer">{s.symbol}: Alpha Vantage adjusted monthly prices</a> · retrieved {s.retrievedAt.slice(0,10)}</li>)}</ul><p>Statistical confidence is limited; it does not establish confidence in future returns. One-year estimates are especially noisy.</p></details>}
 <details><summary>Cash flows, goal and reproducibility</summary><div className="input-grid"><label>Monthly contribution ($; negative for withdrawals)<input type="number" value={input.monthlyContribution??0} onChange={e=>edit({...input,monthlyContribution:Number(e.target.value)})}/></label><label>Ending wealth goal ($)<input type="number" min="1" value={input.goal??""} onChange={e=>edit({...input,goal:e.target.value?Number(e.target.value):undefined})}/></label><label>Random seed<input type="number" min="0" max="4294967295" value={input.seed} onChange={e=>edit({...input,seed:Number(e.target.value)})}/></label></div><p>10,000 paths. Monthly contributions enter at month-end using target weights; withdrawals are proportional and stop at zero. Drawdowns exclude external cash-flow effects and use monthly observations. Goal probability means ending above the goal, not reaching it at any point.</p></details>
 <label className="portfolio-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed the assumptions and understand that simulated probabilities depend on them.</label><button className="action" disabled={!ack||!validWeights||busy} onClick={run}>{busy?"Working…":"Compare 10,000 simulated paths"}</button></section>
 </fieldset>
 <p role="status" aria-live="polite">{message}</p>
 {snapshot&&<PortfolioResults snapshot={snapshot}/>}
 <section className="panel"><h2>Saved simulations</h2><p>Private to this browser’s workspace cookie. Copies in this browser are separate from cloud history. Export a result to retain it independently; exports contain the amounts and assumptions you entered.</p>{saved.length?<ul>{saved.map(s=><li key={s.id}><button disabled={busy} className="action secondary" onClick={()=>open(s)}>{new Date(s.createdAt).toLocaleString()} · {s.names.join(" vs ")}</button></li>)}</ul>:<p>No saved simulations yet.</p>}</section>
 <details className="panel"><summary>Model scope and next phases</summary><p>This is Market Monte Carlo using correlated lognormal monthly asset growth. No fundamental valuation model, historical strategy backtest, tax-lot selection, broker holdings sync, fund holdings look-through, or RSU vesting model is included. Normal log returns omit fat tails, jumps, changing volatility and crisis correlations. No strategy is guaranteed to outperform. Cash has a fixed user-supplied nominal return; inflation and interest-rate changes are not modeled.</p><p>Next phases: stress regimes and more strategies; transaction taxes, account/lot and RSU modeling; then a distinct Fundamental Monte Carlo mode. A company’s research score is not converted into an expected return.</p></details>
 </>;
}
function PortfolioResults({snapshot}:{snapshot:PortfolioSnapshot}){
 const {results,request}=snapshot,[a,b]=results,years=request.input.years,ae=a.years[years].percentiles,be=b.years[years].percentiles;
 function exportRun(){const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`portfolio-${snapshot.id}.json`;link.click();URL.revokeObjectURL(url);}
 return <section className="portfolio-results"><h2>Your decision comparison</h2><p className="eyebrow">{snapshot.modelVersion} · {new Date(snapshot.createdAt).toLocaleString()} · 10,000 paths · nominal USD · pre-tax</p><p className="lede">Compared with {a.name}, {b.name} has {be[3]>=ae[3]?"higher":"lower"} median ending wealth by {wealth(Math.abs(be[3]-ae[3]))} and a {be[1]>=ae[1]?"higher":"lower"} 10th-percentile outcome by {wealth(Math.abs(be[1]-ae[1]))}. Its modeled chance of a monthly-observed drawdown greater than 30% is {percent(b.drawdownProbabilities[1])}, versus {percent(a.drawdownProbabilities[1])}. These are trade-offs under your assumptions, not a winner selection.</p>
 <div className="table-wrap"><table><thead><tr><th>{years}-year outcome</th>{results.map((r,i)=><th key={i}>{r.name}</th>)}</tr></thead><tbody>{[{label:"Lower range · 10th percentile",get:(r:typeof a)=>wealth(r.years[years].percentiles[1])},{label:"Median ending wealth",get:(r:typeof a)=>wealth(r.years[years].percentiles[3])},{label:"Upper range · 90th percentile",get:(r:typeof a)=>wealth(r.years[years].percentiles[5])},{label:"Probability of ending below starting wealth + net contributions",get:(r:typeof a)=>percent(r.lossProbability)},{label:"Probability of >30% drawdown",get:(r:typeof a)=>percent(r.drawdownProbabilities[1])},{label:`Probability of ending above ${wealth(request.input.goal??0)}`,get:(r:typeof a)=>r.goalProbability===null?"No goal set":percent(r.goalProbability)},{label:"Starting allocation volatility",get:(r:typeof a)=>percent(r.annualVolatility)},{label:"Largest starting asset weight",get:(r:typeof a)=>percent(r.largestAssetWeight)}].map(row=><tr key={row.label}><th>{row.label}</th>{results.map((r,i)=><td key={i}>{row.get(r)}</td>)}</tr>)}</tbody></table></div>
 <p className="muted">Probabilities are conditional model frequencies, not observed odds. At 10,000 paths, worst-case Monte Carlo sampling error is approximately ±1 percentage point for a 95% interval; uncertainty about the assumptions can be much larger. Fund concentration is not look-through exposure: VTI and QQQ already include some AMZN and other shared holdings.</p>
 <div className="two-col">{results.map((r,i)=><FanChart key={i} result={r} maxValue={Math.max(1,...results.flatMap(v=>v.years.map(y=>y.percentiles[6])))}/>)}</div>
 <details className="panel"><summary>Ending wealth distributions and all percentiles</summary><div className="two-col">{results.map((r,i)=><Histogram key={i} result={r}/>)}</div><div className="table-wrap"><table><thead><tr><th>Strategy</th><th>Year</th>{[5,10,25,50,75,90,95].map(p=><th key={p}>{p}th percentile</th>)}</tr></thead><tbody>{results.flatMap((r,i)=>r.years.filter(y=>[1,3,5,10,20].includes(y.year)).map(y=><tr key={`${i}-${y.year}`}><th>{r.name}</th><td>{y.year}</td>{y.percentiles.map((v,j)=><td key={j}>{wealth(v)}</td>)}</tr>))}</tbody></table></div></details>
 <details className="panel"><summary>Downside and concentration details</summary><div className="two-col">{results.map((r,i)=><div key={i}><h3>{r.name}</h3><p>Mean maximum drawdown: {percent(r.expectedMaxDrawdown)}. P(drawdown &gt;20% / &gt;30% / &gt;40%): {r.drawdownProbabilities.map(percent).join(" / ")}.</p><p>Average ending wealth in the worst 5% of paths: {wealth(r.worstFivePercentMean)}. This is a wealth level, not the amount lost. Probability of an unfunded withdrawal: {percent(r.unfundedWithdrawalProbability)}.</p><p>Starting holding-level HHI: {r.hhi.toFixed(3)} (sum of squared weights; 1 means one holding). This counts funds and cash as holdings and does not measure sector or underlying single-stock concentration.</p></div>)}</div></details>
 <button className="action secondary" onClick={exportRun}>Export inputs and results</button>
 </section>;
}
