'use client';
import {useState} from 'react';
import type {ResearchRun} from '@/lib/types';
import {investmentDecision} from '@/lib/decision';
export function ReportTools({run}:{run:ResearchRun}){
 const [message,M]=useState('');
 async function share(){const d=investmentDecision(run);const text=[`${run.companyName} (${run.ticker})`, `Research date: ${run.analyzedAt} · ${run.dataMode} data`,`Price: $${run.asOfPrice} as of ${run.marketAsOf||'unavailable'}`,`${d.action} — ${d.score===null?'not rated':d.score+'/100'}`,d.reason,`What changes the decision: ${run.investmentCase?.changeMind||'See report evidence gaps.'}`,`Sources:\n${run.citations.map(c=>c.url).join('\n')}`,'Company research summary. Excludes private holdings and portfolio adjustments.'].join('\n\n');try{await navigator.clipboard.writeText(text);M('Company summary copied. Private holdings are excluded.');}catch{M('Clipboard unavailable. Use the company report on this page.');}}
 return <section className="panel"><h2>Save and share</h2><p>This report is saved by the archive when storage is available. <a href="/research">Open saved reports</a> without generating new research.</p><button onClick={share}>Copy company summary</button><p role="status">{message}</p><details><summary>Research usage and cost</summary>{!run.cost?<p>Usage was not recorded for this older report. Cost is unavailable.</p>:<><p><strong>{run.cost.estimatedUSD===null?'Dollar estimate unavailable':`Estimated generation cost: $${run.cost.estimatedUSD.toFixed(4)}`}</strong></p><p>{run.cost.note}</p>{!run.cost.attempts.length&&<p>No model attempts were recorded for this generation.</p>}<ul>{[...run.cost.attempts].sort((a,b)=>(b.estimatedUSD??0)-(a.estimatedUSD??0)).map((a,i)=><li key={i}><strong>{a.purpose}</strong> · {a.model}: {a.status==='recorded'?`${a.inputTokens?.toLocaleString()} input tokens (${a.cachedTokens??'unknown'} cached), ${a.outputTokens?.toLocaleString()} output tokens; ${a.searchCalls} web calls.`:'Usage unavailable for this attempt.'} {a.estimatedUSD!==undefined?`Estimated $${a.estimatedUSD.toFixed(4)} using prices dated ${a.pricingDate}.`:'Dollar estimate unavailable.'}</li>)}</ul><p>No separate agent charge is added to model and search usage.</p></>}</details></section>;
}
