'use client';
import React, { useState } from 'react';
import type { ResearchRun } from '@/lib/types';
import { distributionSummary, scenarioLabels } from '@/lib/scenario-math';
const usd=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const pct=(n:number)=>`${n>0?'+':''}${n.toFixed(1)}%`;
export function ScenarioDistribution({run}:{run:ResearchRun}) {
  const model=run.scenarioDistribution;
  const ready=!!model?.cases.length;
  const [editing,setEditing]=useState(false);
  const [draft,setDraft]=useState(()=>scenarioLabels.map(label=>({label,price:'',weight:''})));
  const rows=editing ? draft.map(c=>({label:c.label,price:Number(c.price),weight:Number(c.weight)})) : model?.cases??[];
  const summary=editing&&draft.some(c=>c.price.trim()===''||c.weight.trim()==='') ? null : distributionSummary(rows,run.asOfPrice);
  return <section className="panel" aria-labelledby="distribution-heading">
    <p className="eyebrow">POSSIBLE OUTCOMES · 12 MONTHS</p><h2 id="distribution-heading">Severe bear to severe bull</h2>
    <p>{model?.targetDate ? `Through ${model.targetDate}. `:''}Reference price: {run.asOfPrice>0?usd(run.asOfPrice):'unavailable'}{run.marketAsOf?` dated ${run.marketAsOf.slice(0,10)}`:''}.</p>
    <p className="muted">Subjective scenario assumptions, not statistically validated probabilities. Each price is a representative outcome, not a price band or the full range of possible results. Returns exclude dividends, taxes and trading costs.</p>
    {!ready&&!editing&&<><p>A supported five-case price model is not available in this report.</p><ul>{(model?.gaps??['This saved report predates the five-case model. Its original conclusions are preserved.']).map(g=><li key={g}>{g}</li>)}</ul><p>Loss-making, pre-revenue and binary-event companies may need a business-specific valuation model. You can explore your own assumptions below.</p></>}
    <button type="button" className="secondary" onClick={()=>{if(!editing)setDraft(scenarioLabels.map(label=>{const c=model?.cases.find(c=>c.label===label);return {label,price:c?String(c.price):'',weight:c?String(c.weight):''};}));setEditing(!editing);}}>{editing?'Return to report assumptions':'Explore my own scenarios'}</button>
    {editing&&<><p>Your hypothetical inputs stay on this screen, use no AI credits and do not change the saved report or rating. Enter all five prices and weights totaling 100%.</p><div className="input-grid">{draft.map((c,i)=><fieldset key={c.label}><legend>{c.label}</legend><label>Assumed price ($)<input type="number" min="0" step="0.01" value={c.price} onChange={e=>setDraft(draft.map((r,j)=>j===i?{...r,price:e.target.value}:r))}/></label><label>Assumed weight (%)<input type="number" min="0" max="100" step="1" value={c.weight} onChange={e=>setDraft(draft.map((r,j)=>j===i?{...r,weight:e.target.value}:r))}/></label></fieldset>)}</div>{!summary&&<p role="status">Complete the inputs with nonnegative prices and weights totaling 100%.</p>}</>}
    {summary&&<><div className="scenario-grid" aria-live="polite"><div><strong>{usd(summary.price)} · {pct(summary.returnPct)}</strong><p>Weighted outcome under {editing?'your':'report'} assumptions</p></div><div><strong>{summary.gain.toFixed(0)}%</strong><p>Modeled weight of positive returns</p></div><div><strong>{summary.largeLoss.toFixed(0)}%</strong><p>Modeled weight of losing 20% or more</p></div></div><p>Loss: {summary.loss.toFixed(0)}% · unchanged: {summary.flat.toFixed(0)}% · gain of 50% or more: {summary.largeGain.toFixed(0)}%.</p><p className="muted">These percentages sum weights at the representative prices. They do not describe probabilities within price ranges. A high weighted outcome can depend on a small chance of extreme upside.</p></>}
    {rows.length>0&&summary&&<div className="table-wrap"><table><thead><tr><th>Case</th><th>Assumed weight</th><th>Representative price</th><th>Price return</th><th>What happens</th></tr></thead><tbody>{rows.map(c=><tr key={c.label}><th scope="row">{c.label}</th><td><meter min="0" max="100" value={c.weight} aria-label={`${c.label} weight`}/>{' '}{c.weight}%</td><td>{usd(c.price)}</td><td>{run.asOfPrice>0?pct((c.price/run.asOfPrice-1)*100):'Unavailable'}</td><td>{editing?'Your hypothetical outcome':model?.cases.find(r=>r.label===c.label)?.drivers}</td></tr>)}</tbody></table></div>}
    {ready&&!editing&&<details><summary>Valuation inputs, sources and assumed weights</summary><p>{model!.basis}. {model!.weightReason}</p><p>Source links and dates establish provenance, not independent verification. Prices are calculated from the stated assumptions.</p>{model!.cases.map(c=><article key={c.label}><h3>{c.label}</h3><p>{c.startingEvidence} · evidence dated {c.evidenceDate}</p><p><strong>Proposed assumptions:</strong> {c.assumptions}</p><p>Metric per future diluted share {usd(c.metricPerShare)} × {c.multiple.toFixed(2)}{model!.basis==='Revenue per share × EV/sales'?` + net cash per share ${usd(c.netCashPerShare)}`:''} = {usd(c.price)} (floored at zero).</p>{c.sources.map((s,i)=><span key={s}><a href={s} target="_blank" rel="noreferrer">Source {i+1}</a>{' '}</span>)}</article>)}{model!.gaps.length>0&&<ul>{model!.gaps.map(g=><li key={g}>{g}</li>)}</ul>}</details>}
    <div className="two-col"><div><h3>Why it could rise</h3>{run.highlights.length?<ul>{run.highlights.slice(0,3).map(g=><li key={g}>{g}</li>)}</ul>:<p>Supporting evidence unavailable.</p>}</div><div><h3>Why it could fall</h3>{run.risks.length?<ul>{run.risks.slice(0,3).map(g=><li key={g}>{g}</li>)}</ul>:<p>Risk evidence unavailable.</p>}</div></div>
    {run.investmentCase&&<><p><strong>Entry or wait condition:</strong> {run.investmentCase.timing}</p><p><strong>What changes the decision:</strong> {run.investmentCase.changeMind}</p></>}
  </section>;
}
