import {expect,it} from "vitest";
import {estimateHistory,parseAlphaHistory,type History} from "../lib/portfolio/history";
import {requestSchema,runPortfolio} from "../lib/portfolio/model";
function history(symbol:string,scale=1):History{return {symbol,adjusted:true,source:"https://example.com",retrievedAt:"2026-09-27T00:00:00Z",prices:Array.from({length:61},(_,i)=>{const date=new Date(Date.UTC(2021,7+i,28)).toISOString().slice(0,10);return {date,close:100*Math.exp(.01*i+scale*.03*Math.sin(i))};})};}
it("aligns completed months, estimates correlation and keeps cash deterministic",()=>{const e=estimateHistory([history("A"),history("B")],["A","B","CASH"],5,new Date("2026-09-27"));expect(e.observations).toBe(60);expect(e.correlation[0][1]).toBeCloseTo(1);expect(e.correlation[0][2]).toBe(0);expect(e.assets[2].volatility).toBe(0);expect(e.assets[0].volatility).toBeGreaterThan(0);});
it("does not silently shorten missing history or bridge missing months",()=>{const h=history("A");h.prices.splice(10,1);expect(()=>estimateHistory([h],["A"],5,new Date("2026-09-27"))).toThrow("Need");});
it("rejects stale history",()=>{expect(()=>estimateHistory([history("A")],["A"],1,new Date("2027-01-01"))).toThrow("stale");});
it("rejects mismatched ticker, raw close only, and invalid dates",()=>{expect(()=>parseAlphaHistory({"Meta Data":{"2. Symbol":"B"}},"A")).toThrow("match");expect(()=>parseAlphaHistory({"Meta Data":{"2. Symbol":"A"},"Monthly Adjusted Time Series":{"2026-02-30":{"5. adjusted close":"10"}}},"A")).toThrow("Invalid");});
it("excludes current partial month and reads adjusted rather than raw close",()=>{const h=parseAlphaHistory({"Meta Data":{"2. Symbol":"A"},"Monthly Adjusted Time Series":{"2026-08-31":{"4. close":"200","5. adjusted close":"100"},"2026-09-25":{"5. adjusted close":"110"}}},"A",new Date("2026-09-27"));expect(h.prices).toEqual([{date:"2026-08-31",close:100}]);});
it("requires acknowledged assumptions and bounds public API work",()=>{expect(requestSchema.safeParse({input:{paths:100000},assumptions:{acknowledged:false}}).success).toBe(false);});
it("produces persisted summaries without all raw paths",()=>{const r=runPortfolio({input:{assets:[{symbol:"CASH",expectedReturn:0,volatility:0}],correlation:[[1]],strategies:[{name:"A",weights:[1],rebalance:"none"},{name:"B",weights:[1],rebalance:"none"}],initialValue:1000,years:5,paths:10000,seed:1},assumptions:{returnSource:"User assumption",riskSource:"Deterministic cash",acknowledged:true}});expect(r.results[0]).not.toHaveProperty("endingValues");expect(r.results[0].histogram.reduce((a,b)=>a+b.count,0)).toBe(10000);expect(r.results[0].years[5].percentiles[3]).toBe(1000);});
