import type { ResearchRun } from "./types";

export { singleInvestmentDecision as investmentDecision } from "./investment";

function money(n: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(n); }
export function plainSummary(run: ResearchRun) {
  if (run.executiveSummary) return run.executiveSummary;
  const financials = run.annualFinancials;
  const lines: string[] = [];
  if (financials) {
    if (financials.revenue != null) lines.push(`For the year ending ${financials.periodEnd}, the company reported ${money(financials.revenue)} in sales.`);
    if (financials.netIncome != null) lines.push(`It reported ${financials.netIncome < 0 ? "a loss" : "a profit"} of ${money(Math.abs(financials.netIncome))}.`);
    if (financials.freeCashFlow != null) lines.push(financials.freeCashFlow < 0 ? `Cash spent on equipment and other long-term assets exceeded operating cash generated by ${money(-financials.freeCashFlow)}. How that spending is funded matters.` : `After cash spending on long-term assets, ${money(financials.freeCashFlow)} of operating cash remained. This is a cash-flow measure, not a forecast.`);
  }
  return {
    overview: lines.join(" ") || "The report does not contain enough verified financial information to explain how this company is doing.",
    strength: run.highlights[0] || "No clear business strength has been established from the available evidence.",
    concern: run.risks[0] || "The evidence is incomplete, so key risks may still be missing.",
    watchFor: "Check the next earnings report, cash generation and a defensible valuation before changing the decision.",
  };
}

export type CallInputs = { strategy: "call" | "spread"; strike: number; shortStrike?: number; debit: number; contracts: number; targetPrice: number; expiration: string; budget: number };
export function callPayoff(input: CallInputs, today = new Date().toISOString().slice(0, 10)) {
  const { strike, shortStrike, debit, contracts, targetPrice, expiration, budget } = input;
  if (![strike, debit, contracts, targetPrice, budget].every(Number.isFinite) || strike <= 0 || debit <= 0 || targetPrice < 0 || budget <= 0 || contracts < 1 || !Number.isInteger(contracts) || contracts > 1000) throw new Error("Enter positive prices, a loss budget and a whole number of contracts.");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(expiration) || !Number.isFinite(Date.parse(expiration)) || new Date(expiration).toISOString().slice(0, 10) !== expiration || expiration <= today) throw new Error("Choose a valid future expiration date.");
  const spread = input.strategy === "spread";
  if (spread && (!Number.isFinite(shortStrike) || shortStrike! <= strike || debit >= shortStrike! - strike)) throw new Error("For a call debit spread, the short strike must exceed the long strike and the net debit must be less than the strike difference.");
  const multiplier = 100 * contracts;
  const maxLoss = debit * multiplier;
  if (![maxLoss, strike + debit, targetPrice * multiplier].every(Number.isFinite)) throw new Error("The entered values are too large to calculate safely.");
  const intrinsic = Math.max(targetPrice - strike, 0) - (spread ? Math.max(targetPrice - shortStrike!, 0) : 0);
  return { maxLoss, breakEven: strike + debit, maxGain: spread ? (shortStrike! - strike - debit) * multiplier : null,
    profitAtTarget: (intrinsic - debit) * multiplier, budgetExceeded: maxLoss > budget,
    affordableContracts: Math.floor(budget / (debit * 100)), daysToExpiry: Math.round((Date.parse(expiration) - Date.parse(today)) / 86400000) };
}
